// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcOYx2YF7jUJxQgFioyGI3GERIf9AoOw',
    appId: '1:956265657284:web:1532361c88be767a36ea91',
    messagingSenderId: '956265657284',
    projectId: 'carers-df994',
    authDomain: 'carers-df994.firebaseapp.com',
    storageBucket: 'carers-df994.appspot.com',
    measurementId: 'G-LL6D4H3EHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbKA8gqpgNQA-HPlmuos8W0hXJdfqg1uU',
    appId: '1:956265657284:android:2f18dac7f607f7d036ea91',
    messagingSenderId: '956265657284',
    projectId: 'carers-df994',
    storageBucket: 'carers-df994.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLrr4WSKFOXsRdesy9SWr-8CRQwq9CVQA',
    appId: '1:956265657284:ios:2d1412d3e85d624336ea91',
    messagingSenderId: '956265657284',
    projectId: 'carers-df994',
    storageBucket: 'carers-df994.appspot.com',
    iosClientId: '956265657284-i2ju82r2os1bj8qfharsesl2lghimcoa.apps.googleusercontent.com',
    iosBundleId: 'tk.piscos.carers',
  );
}
